### ISSUE TITLE
How can we integrate React Native SDK with our RN App... 

### ISSUE THREAD

**Issue by mushtaque87** [Tap-Payments/gosellSDK-ReactNative#1]
How can we integrate React Native SDK with our RN App... Currently we are using goSellSDK-AndroidX and use TapPayment.openTapPaymentUI(tapCompanyData) API .. Whats the difference in this project. Do you have a sample project for this.

And is it using the latest version 3.11 ?

**Comment by kareemTap** [comment]
@mushtaque87 
Yes, you can add our package as a dependency using **NPM**
You will use it instead of the Android sdk.
You have the choice to use the React-Native or use the Android SDK, both will give the same functionality.

**Comment by kareemTap** [comment]
Closed since not getting a response so I think the issue has been fixed.
