### ISSUE TITLE
Example is not working on ios

### ISSUE THREAD

**Issue by arunmt024** [Tap-Payments/gosellSDK-ReactNative#11]
its return  { sdk_result: 'FAILED', trx_mode: 'CHARGE' }

**Comment by Abdulla97** [comment]
this should be due to object configuration or you don't have the mobile SDKs keys (ask the support to get them) to get more info about the error run the project using Xcode the error log there will have more info

**Comment by kareemTap** [comment]
@arunmt024 You need to contact our support team to get valid keys and register your project BundleId.
