### ISSUE TITLE
Save card checkbox does not return customer_id 

### ISSUE THREAD

**Issue by ramisalem** [Tap-Payments/gosellSDK-ReactNative#13]
Hello, I would like to  allow user to save his/her card so that he/she can use it latter,  and  In order to display the saved cards for each user, I should pass the customer_id to in customer object 
 but the SDK result does not return customer_id in CHARGE, AUTHORIZE, and TOKENIZE modes 
![simulator_screenshot_159BC3A0-11B2-4B22-AF08-C2F124AAD5C0](https://user-images.githubusercontent.com/25037017/115107280-b76ad800-9f1e-11eb-91c8-3d55a5226f13.png)

**Comment by kareemTap** [comment]
@ramisalem Customer details have been added to the response in the latest release 1.0.7

**Comment by ramisalem** [comment]
@kareemTap  Hi, I updated the package to the lastest and it worked

**Comment by kareemTap** [comment]
@ramisalem Great
