### ISSUE TITLE
 RCTBridge required dispatch_sync to load RCTDevLoadingView. This may lead to deadlocks 

### ISSUE THREAD

**Issue by ramisalem** [Tap-Payments/gosellSDK-ReactNative#15]
Hello, I am integrating this library all fine but due to this warning the app crashed after  opening the payment page more then one time 

![simulator_screenshot_1CB919A2-9332-4261-8E3E-1CD7336D2E0C](https://user-images.githubusercontent.com/25037017/116789649-ba101600-aa64-11eb-9b27-d17ef8ae287b.png)

**Comment by kareemTap** [comment]
@ramisalem Can you please provide us with the version you're using?

**Comment by ramisalem** [comment]
@kareemTap   Sorry  I  found out The issue is not related to this library
