### ISSUE TITLE
Tap-Payments not support new architecture  for react-native 

### ISSUE THREAD

**Issue by moGeekHex** [Tap-Payments/gosellSDK-ReactNative#29]
After upgrade react-native to "0.70.1" show  error "Cannot read property 'startPayment' of null"

**Comment by MahmoudElmoghazy** [comment]
@moGeekHex Any updates about this ?

**Comment by MahmoudElmoghazy** [comment]
@Sabbaghh @moGeekHex Add this line to the pod file 
  pod 'RNGosellSdkReactNative', :path => '../node_modules/@tap-payments/gosell-sdk-react-native/ios'

**Comment by UmairK11** [comment]
I'm facing the same problem on Android. I'm using these versions:

@tap-payments/gosell-sdk-react-native: ^2.3.48

react-native: 0.73.5
