### ISSUE TITLE
fatalError("There is no \(Constants.goSellSDKResourcesBundleName) bundle.") In IOS

### ISSUE THREAD

**Issue by ramisalem** [Tap-Payments/gosellSDK-ReactNative#8]
Hello, Good day, 

I am getting fatalError("There is no \(Constants.goSellSDKResourcesBundleName) bundle.") in Xcode after calling startPayment method 

![Screenshot 2021-01-18 at 8 57 04 AM](https://user-images.githubusercontent.com/25037017/104869246-93bde300-596b-11eb-9a08-e15aa0d6fa46.png)

[here is the sentry log for more details]  (https://sentry.io/share/issue/dc2d00acd3364db59a284d463c43250d/)

 ```  startSDK() {
    console.log('start SDK');
    console.log(this.sdkModule, this.sdkModule.startPayment);

    this.sdkModule &&
      this.sdkModule.startPayment(sdkConfigurations, this.handleResult);
  } 

 log is 

 {"getConstants": [Function anonymous], "kareem": [Function nonPromiseMethodWrapper], "startPayment": [Function nonPromiseMethodWrapper]} undefined
``` 

what I did 
1) I have cloned the repo and tried the example, firstly it does not work till I removed 
"\"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)\"",
From LIBRARY_SEARCH_PATHS 

2) I tried the same js code  in my project,  I got the above error 

Thanks in advance

**Comment by kareemTap** [comment]
@ramisalem Can you please try to use the latest version?
It should work properly.

**Comment by kareemTap** [comment]
Closed since we didn't get a reply so we are expecting the issue is solved.
